-- Baseline schema, matching what Hibernate's ddl-auto=update had already created for
-- users/events/subscriptions. From here on, schema changes go through new migrations.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    role VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(30) NOT NULL,
    description VARCHAR(300),
    location VARCHAR(100) NOT NULL,
    capacity INTEGER NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    image_url VARCHAR(500),
    status VARCHAR(16) NOT NULL,
    type VARCHAR(20),
    organizer_id BIGINT NOT NULL,
    CONSTRAINT fk_events_organizer FOREIGN KEY (organizer_id) REFERENCES users(id)
);

CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    CONSTRAINT fk_subscriptions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_subscriptions_event FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT uk_subscriptions_user_event UNIQUE (user_id, event_id)
);
