-- Favoritos: um bookmark sem compromisso, distinto de subscriptions (que representa uma
-- inscrição real, sujeita a capacidade/estado/datas). Sem restrições de estado ou data.

CREATE TABLE favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_favorites_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_favorites_event FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT uk_favorites_user_event UNIQUE (user_id, event_id)
);

CREATE INDEX idx_favorites_user ON favorites(user_id);
