spring:
  profiles:
    active: dev  # por agora trabalhamos sempre em H2
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  upload:
    dir: ./uploads
  mail:
    enabled: false
    from: no-reply@vlink.pt
    reminder-window-hours: 24
    reminder-cron: "0 */15 * * * *"

logging:
  level:
    org.hibernate.SQL: warn
